# Generated by Django 4.1 on 2022-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='payment_pic',
            field=models.ImageField(upload_to='payment/'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='your_pic',
            field=models.ImageField(upload_to='user_pic/'),
        ),
    ]
